apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-gpu
  labels:
    app: jupyter-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-gpu
  template:
    metadata:
      labels:
        app: jupyter-gpu
    spec:
      containers:
      - name: jupyter-gpu
        image: jupyter-gpu:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: hostvol
          mountPath: /home/meng/work
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
        - name: hostvol
          hostPath:
            path: /home/meng/Project
