apiVersion: v1
kind: Service
metadata:
  name: jupyter-gpu-service
  labels:
    app: jupyter-gpu
spec:
  type: LoadBalancer
  selector:
    app: jupyter-gpu
  ports:
  - protocol: TCP
    port: 8888
